version: '3.0'

services:
  db:
    image: postgres:15
    container_name: db
    volumes:
      - /fast_api/docker/db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    env_file:
      - .env
    ports:
      - 80:80