"""Database creation

Revision ID: 7344ce1b372b
Revises: 
Create Date: 2023-12-27 00:51:32.779577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7344ce1b372b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_levels',
                sa.Column('id', sa.Integer(), nullable=False),
                sa.Column('level_name', sa.String(), nullable=True),
                sa.Column('required_days', sa.Integer(), nullable=True),
                sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
                sa.Column('id', sa.UUID(), nullable=False),
                sa.Column('email', sa.String(), nullable=False),
                sa.Column('username', sa.String(), nullable=False),
                sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                sa.Column('lvl', sa.Integer(), nullable=True),
                sa.Column('hashed_password', sa.String(length=1024), nullable=False),
                sa.Column('is_active', sa.Boolean(), nullable=False),
                sa.Column('is_superuser', sa.Boolean(), nullable=False),
                sa.Column('is_verified', sa.Boolean(), nullable=False),
                sa.ForeignKeyConstraint(['lvl'], ['access_levels.id'], ),
                sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('access_levels')
    # ### end Alembic commands ###
